/-!
Hiroshima Responsibility Functor, minimal Lean formalization.

This is the "100 point" version of the sketch:

* C is the free category generated by D --p--> P --q--> O.
* R is the free category generated by
  DH --m--> PH --b--> B --e--> E --v--> V --a--> A --o--> OR.
* DH means "corporate decision under Hiroshima place-context".
* PH means "profit/efficiency evaluation under Hiroshima place-context".
* The Hiroshima responsibility functor F_H : C -> R maps:
    D |-> DH, P |-> PH, O |-> OR,
    p |-> m,
    q |-> o o a o v o e o b.
* Therefore F_H(q o p) is the responsibility composite
  DH -> PH -> B -> E -> V -> A -> OR.
* Adm_BV is represented by paths that factor through both B and V.
* Exclusion is universal: any path that fails to pass B or V is inadmissible.
* Hiroshima's historical witness is recorded as an explicit external axiom,
  not as a theorem proved by category theory.

No empirical or psychological claim is proved here.  The theorem-level claim is
that paths bypassing Beacon or Verification are excluded from Adm_BV.
-/

namespace HiroshimaResponsibility

inductive CObj where
  | D      -- corporate decision
  | P      -- profit / efficiency evaluation
  | O      -- ordinary operational outcome
  deriving DecidableEq, Repr

inductive CEdge : CObj -> CObj -> Type where
  | p : CEdge CObj.D CObj.P
  | q : CEdge CObj.P CObj.O

inductive CPath : CObj -> CObj -> Type where
  | id : CPath x x
  | step : CEdge x y -> CPath y z -> CPath x z

namespace CPath

def comp : CPath x y -> CPath y z -> CPath x z
  | id, q => q
  | step edge p, q => step edge (comp p q)

theorem id_comp (p : CPath x y) : comp id p = p := by
  rfl

theorem comp_id (p : CPath x y) : comp p id = p := by
  induction p with
  | id => rfl
  | step edge rest ih =>
      simp [comp, ih]

theorem comp_assoc (p : CPath w x) (q : CPath x y) (r : CPath y z) :
    comp (comp p q) r = comp p (comp q r) := by
  induction p with
  | id => rfl
  | step edge rest ih =>
      simp [comp, ih]

end CPath

inductive RObj where
  | DH     -- Hiroshima-contextualized corporate decision
  | PH     -- Hiroshima-contextualized profit / efficiency evaluation
  | B      -- Beacon admissibility condition
  | E      -- evidence
  | V      -- verifiable evidence / third-party verification
  | A      -- accountable decision
  | OR     -- accountable operational outcome O'
  deriving DecidableEq, Repr, BEq

inductive REdge : RObj -> RObj -> Type where
  | m : REdge RObj.DH RObj.PH
  | b : REdge RObj.PH RObj.B
  | e : REdge RObj.B RObj.E
  | v : REdge RObj.E RObj.V
  | a : REdge RObj.V RObj.A
  | o : REdge RObj.A RObj.OR

  -- Explicit bypass edges used to prove exclusion from Adm_BV.
  | bypassBeacon : REdge RObj.PH RObj.E
  | bypassVerification : REdge RObj.E RObj.A

inductive RPath : RObj -> RObj -> Type where
  | id : RPath x x
  | step : REdge x y -> RPath y z -> RPath x z

namespace RPath

def comp : RPath x y -> RPath y z -> RPath x z
  | id, q => q
  | step edge p, q => step edge (comp p q)

theorem id_comp (p : RPath x y) : comp id p = p := by
  rfl

theorem comp_id (p : RPath x y) : comp p id = p := by
  induction p with
  | id => rfl
  | step edge rest ih =>
      simp [comp, ih]

theorem comp_assoc (p : RPath w x) (q : RPath x y) (r : RPath y z) :
    comp (comp p q) r = comp p (comp q r) := by
  induction p with
  | id => rfl
  | step edge rest ih =>
      simp [comp, ih]

-- The visited objects of a path, including the starting object and endpoint.
def pathObjects : {x y : RObj} -> RPath x y -> List RObj
  | x, _, id => [x]
  | x, _, step _ rest => x :: pathObjects rest

end RPath

open CEdge CPath REdge RPath

-- The ordinary corporate composite u = q o p : D -> O.
def ordinaryDecision : CPath CObj.D CObj.O :=
  CPath.step CEdge.p (CPath.step CEdge.q CPath.id)

-- The responsibility tail F_H(q) = o o a o v o e o b : PH -> OR.
def responsibilityTail : RPath RObj.PH RObj.OR :=
  RPath.step REdge.b
    (RPath.step REdge.e
    (RPath.step REdge.v
    (RPath.step REdge.a
    (RPath.step REdge.o RPath.id))))

-- The full responsibility composite DH -> PH -> B -> E -> V -> A -> OR.
def responsibilityComposite : RPath RObj.DH RObj.OR :=
  RPath.step REdge.m responsibilityTail

-- Hiroshima Responsibility Functor F_H on objects.
def FHObj : CObj -> RObj
  | CObj.D => RObj.DH
  | CObj.P => RObj.PH
  | CObj.O => RObj.OR

-- Hiroshima Responsibility Functor F_H on generating morphisms.
def FHEdge : CEdge x y -> RPath (FHObj x) (FHObj y)
  | CEdge.p => RPath.step REdge.m RPath.id
  | CEdge.q => responsibilityTail

-- Extension of F_H to all paths in the free category C.
def FHPath : CPath x y -> RPath (FHObj x) (FHObj y)
  | CPath.id => RPath.id
  | CPath.step edge rest => RPath.comp (FHEdge edge) (FHPath rest)

theorem functor_preserves_id :
    FHPath (CPath.id : CPath x x) = RPath.id := by
  rfl

theorem functor_preserves_comp (p : CPath x y) (q : CPath y z) :
    FHPath (CPath.comp p q) = RPath.comp (FHPath p) (FHPath q) := by
  induction p with
  | id => rfl
  | step edge rest ih =>
      simp [CPath.comp, FHPath, RPath.comp_assoc, ih]

theorem FH_maps_ordinary_to_responsibility :
    FHPath ordinaryDecision = responsibilityComposite := by
  rfl

def passesThroughB (p : RPath x y) : Prop :=
  List.Mem RObj.B (RPath.pathObjects p)

def passesThroughV (p : RPath x y) : Prop :=
  List.Mem RObj.V (RPath.pathObjects p)

-- Adm_BV(X,Y): admissible responsible paths factor through both B and V.
def AdmBV (p : RPath x y) : Prop :=
  passesThroughB p /\ passesThroughV p

-- The LaTeX definition of Adm_BV: factorization through B and then V.
def AdmBV_factorizes (p : RPath x y) : Prop :=
  Exists (fun (pre : RPath x RObj.B) =>
  Exists (fun (middle : RPath RObj.B RObj.V) =>
  Exists (fun (suffix : RPath RObj.V y) =>
    p = RPath.comp (RPath.comp pre middle) suffix)))

def FactorsThrough (obj : RObj) (p : RPath x y) : Prop :=
  Exists (fun (pre : RPath x obj) =>
  Exists (fun (suffix : RPath obj y) =>
    p = RPath.comp pre suffix))

-- If an object occurs in pathObjects p, then p splits at that object.
theorem splitAtObj (obj : RObj) (p : RPath x y) :
    List.Mem obj (RPath.pathObjects p) -> FactorsThrough obj p := by
  induction p with
  | id =>
      intro h
      cases h with
      | head =>
          exact Exists.intro RPath.id (Exists.intro RPath.id rfl)
      | tail _ htail =>
          cases htail
  | step edge rest ih =>
      intro h
      cases h with
      | head =>
          exact Exists.intro RPath.id (Exists.intro (RPath.step edge rest) rfl)
      | tail _ hrest =>
          cases ih hrest with
          | intro pre restProof =>
              cases restProof with
              | intro suffix hs =>
                  exact Exists.intro (RPath.step edge pre)
                    (Exists.intro suffix (by simp [RPath.comp, hs]))

theorem splitAtB (p : RPath x y) :
    passesThroughB p -> FactorsThrough RObj.B p :=
  splitAtObj RObj.B p

theorem splitAtV (p : RPath x y) :
    passesThroughV p -> FactorsThrough RObj.V p :=
  splitAtObj RObj.V p

theorem pathObjects_start (p : RPath x y) :
    List.Mem x (RPath.pathObjects p) := by
  cases p with
  | id =>
      apply List.Mem.head
  | step edge rest =>
      apply List.Mem.head

theorem comp_contains_junction
    (pre : RPath x obj) (suffix : RPath obj y) :
    List.Mem obj (RPath.pathObjects (RPath.comp pre suffix)) := by
  induction pre with
  | id =>
      exact pathObjects_start suffix
  | step edge rest ih =>
      apply List.Mem.tail
      exact ih suffix

theorem noB_from_OR (p : RPath RObj.OR y) : Not (passesThroughB p) := by
  cases p with
  | id =>
      intro h
      cases h with
      | tail _ htail => cases htail
  | step edge rest =>
      cases edge

theorem noB_from_A (p : RPath RObj.A y) : Not (passesThroughB p) := by
  cases p with
  | id =>
      intro h
      cases h with
      | tail _ htail => cases htail
  | step edge rest =>
      cases edge
      intro h
      cases h with
      | tail _ htail => exact noB_from_OR rest htail

theorem noB_from_V (p : RPath RObj.V y) : Not (passesThroughB p) := by
  cases p with
  | id =>
      intro h
      cases h with
      | tail _ htail => cases htail
  | step edge rest =>
      cases edge
      intro h
      cases h with
      | tail _ htail => exact noB_from_A rest htail

theorem noB_from_E (p : RPath RObj.E y) : Not (passesThroughB p) := by
  cases p with
  | id =>
      intro h
      cases h with
      | tail _ htail => cases htail
  | step edge rest =>
      cases edge
      case v =>
        intro h
        cases h with
        | tail _ htail => exact noB_from_V rest htail
      case bypassVerification =>
        intro h
        cases h with
        | tail _ htail => exact noB_from_A rest htail

theorem factorizes_to_AdmBV (p : RPath x y) :
    AdmBV_factorizes p -> AdmBV p := by
  intro h
  cases h with
  | intro pre hmiddle =>
      cases hmiddle with
      | intro middle hsuffix =>
          cases hsuffix with
          | intro suffix heq =>
              rw [heq]
              unfold AdmBV passesThroughB passesThroughV
              constructor
              case left =>
                rw [RPath.comp_assoc]
                exact comp_contains_junction pre (RPath.comp middle suffix)
              case right =>
                exact comp_contains_junction (RPath.comp pre middle) suffix

theorem AdmBV_to_factorizes (p : RPath x y) :
    AdmBV p -> AdmBV_factorizes p := by
  induction p with
  | id =>
      intro h
      unfold AdmBV passesThroughB passesThroughV at h
      cases h.left with
      | head =>
          cases h.right with
          | tail _ htail => cases htail
      | tail _ htail => cases htail
  | step edge rest ih =>
      intro h
      cases edge
      case m =>
        have hrest : AdmBV rest := by
          unfold AdmBV passesThroughB passesThroughV at *
          constructor
          case left =>
            cases h.left with
            | tail _ hb => exact hb
          case right =>
            cases h.right with
            | tail _ hv => exact hv
        cases ih hrest with
        | intro pre hmiddle =>
            cases hmiddle with
            | intro middle hsuffix =>
                cases hsuffix with
                | intro suffix heq =>
                    exact Exists.intro (RPath.step REdge.m pre)
                      (Exists.intro middle
                      (Exists.intro suffix (by simp [RPath.comp, heq])))
      case b =>
        have hVrest : passesThroughV rest := by
          unfold AdmBV passesThroughV at h
          cases h.right with
          | tail _ hv => exact hv
        cases splitAtV rest hVrest with
        | intro middle hsuffix =>
            cases hsuffix with
            | intro suffix heq =>
                exact Exists.intro (RPath.step REdge.b RPath.id)
                  (Exists.intro middle
                  (Exists.intro suffix (by simp [RPath.comp, heq])))
      case e =>
        cases splitAtV (RPath.step REdge.e rest) h.right with
        | intro middle hsuffix =>
            cases hsuffix with
            | intro suffix heq =>
                exact Exists.intro RPath.id
                  (Exists.intro middle
                  (Exists.intro suffix (by simp [RPath.comp, heq])))
      case v =>
        have hBrest : passesThroughB rest := by
          unfold AdmBV passesThroughB at h
          cases h.left with
          | tail _ hb => exact hb
        exact False.elim (noB_from_V rest hBrest)
      case a =>
        have hBrest : passesThroughB rest := by
          unfold AdmBV passesThroughB at h
          cases h.left with
          | tail _ hb => exact hb
        exact False.elim (noB_from_A rest hBrest)
      case o =>
        have hBrest : passesThroughB rest := by
          unfold AdmBV passesThroughB at h
          cases h.left with
          | tail _ hb => exact hb
        exact False.elim (noB_from_OR rest hBrest)
      case bypassBeacon =>
        have hBrest : passesThroughB rest := by
          unfold AdmBV passesThroughB at h
          cases h.left with
          | tail _ hb => exact hb
        exact False.elim (noB_from_E rest hBrest)
      case bypassVerification =>
        have hBrest : passesThroughB rest := by
          unfold AdmBV passesThroughB at h
          cases h.left with
          | tail _ hb => exact hb
        exact False.elim (noB_from_A rest hBrest)

theorem AdmBV_iff_factorizes (p : RPath x y) :
    AdmBV p <-> AdmBV_factorizes p := by
  constructor
  case mp =>
    exact AdmBV_to_factorizes p
  case mpr =>
    exact factorizes_to_AdmBV p

-- Universal exclusion: any path omitting B or V is inadmissible.
theorem not_passB_not_admissible
    (p : RPath x y) (h : Not (passesThroughB p)) : Not (AdmBV p) := by
  intro hp
  exact h hp.left

theorem not_passV_not_admissible
    (p : RPath x y) (h : Not (passesThroughV p)) : Not (AdmBV p) := by
  intro hp
  exact h hp.right

theorem responsibilityComposite_admissible :
    AdmBV responsibilityComposite := by
  unfold AdmBV passesThroughB passesThroughV responsibilityComposite
    responsibilityTail RPath.pathObjects
  exact And.intro
    (by
      apply List.Mem.tail
      apply List.Mem.tail
      apply List.Mem.head)
    (by
      apply List.Mem.tail
      apply List.Mem.tail
      apply List.Mem.tail
      apply List.Mem.tail
      apply List.Mem.head)

-- A path DH -> PH -> E -> V -> A -> OR skips Beacon.
def bypassBeaconPath : RPath RObj.DH RObj.OR :=
  RPath.step REdge.m
    (RPath.step REdge.bypassBeacon
    (RPath.step REdge.v
    (RPath.step REdge.a
    (RPath.step REdge.o RPath.id))))

-- A path DH -> PH -> B -> E -> A -> OR skips Verification.
def bypassVerificationPath : RPath RObj.DH RObj.OR :=
  RPath.step REdge.m
    (RPath.step REdge.b
    (RPath.step REdge.e
    (RPath.step REdge.bypassVerification
    (RPath.step REdge.o RPath.id))))

theorem bypassBeacon_not_admissible :
    Not (AdmBV bypassBeaconPath) := by
  apply not_passB_not_admissible
  change Not (List.Mem RObj.B
    [RObj.DH, RObj.PH, RObj.E, RObj.V, RObj.A, RObj.OR])
  intro h
  cases h with
  | tail _ h =>
      cases h with
      | tail _ h =>
          cases h with
          | tail _ h =>
              cases h with
              | tail _ h =>
                  cases h with
                  | tail _ h =>
                      cases h with
                      | tail _ h => cases h

theorem bypassVerification_not_admissible :
    Not (AdmBV bypassVerificationPath) := by
  apply not_passV_not_admissible
  change Not (List.Mem RObj.V
    [RObj.DH, RObj.PH, RObj.B, RObj.E, RObj.A, RObj.OR])
  intro h
  cases h with
  | tail _ h =>
      cases h with
      | tail _ h =>
          cases h with
          | tail _ h =>
              cases h with
              | tail _ h =>
                  cases h with
                  | tail _ h =>
                      cases h with
                      | tail _ h => cases h

/-!
## External Historical Axioms

These predicates and witness axioms cannot be proved by category theory.  They
record historical and institutional facts that motivate the Hiroshima subscript
in F_H and the civilizational-layer examples below.

* `CivilizationalScale` : the consequence of a decision path was large enough
  to qualify as civilizational-scale harm.
  Historical referent: the atomic bombing of Hiroshima, August 1945.

* `WorldMemory` : the consequence of a decision path is preserved as
  institutionalized world memory, not merely as historical record.
  Historical referent: Hiroshima Peace Memorial / Genbaku Dome
  (UNESCO World Heritage, https://whc.unesco.org/en/list/775/) and the
  Hiroshima National Peace Memorial Hall for the Atomic Bomb Victims
  (https://www.hiro-tsuitokinenkan.go.jp/en/about/).

* `HiroshimaAIProcessAnchor` : the city of Hiroshima is already used as an
  international AI governance reference point.
  Historical referent: the G7 Hiroshima AI Process launched under Japan's G7
  presidency in 2023.
  Source: https://www.oecd.org/en/publications/
          g7-hiroshima-process-on-generative-artificial-intelligence-ai_bf3c0c60-en.html

The conjunction of these conditions is what structurally justifies the
subscript H in F_H.  No other city is treated here as satisfying this
conjunction simultaneously.
-/

-- Predicate: the path's realized consequence was civilizational-scale.
-- Historical referent: Hiroshima, August 1945.
axiom CivilizationalScale : RPath RObj.DH RObj.OR -> Prop

-- Predicate: the path's consequence is preserved as institutional world memory
-- and not merely archived as historical data.
-- Historical referent: Hiroshima Peace Memorial institutions.
axiom WorldMemory : RPath RObj.DH RObj.OR -> Prop

-- Proposition: Hiroshima is an anchor point for international AI governance
-- through the G7 Hiroshima AI Process (2023).
axiom HiroshimaAIProcessAnchor : Prop

-- The Hiroshima historical witness axiom.
-- Asserts:
--   (a) there exists a decision path that was historically realized as
--       non-admissible, caused civilizational-scale harm, and is preserved as
--       world memory, all localized in Hiroshima; and
--   (b) Hiroshima is an existing AI governance anchor.
-- This axiom is the sole bridge between the formal model and the historical
-- reality that gives F_H its H.
axiom hiroshima_historical_witness :
  (Exists fun decision : RPath RObj.DH RObj.OR =>
    Not (AdmBV decision) /\
    CivilizationalScale decision /\
    WorldMemory decision) /\
  HiroshimaAIProcessAnchor

/-!
## Civilizational Responsibility Technology

The formal point is not to compare two identical Boolean records, and not to
use `True` placeholders.  Instead, a technology is placed in the
civilizational-responsibility layer only when it has witnesses for real
constraints in the existing formal structure:

1. an inadmissible decision path in R;
2. an inadmissible decision path with civilizational-scale consequences.

This is the formal content of "nuclear weapons and AI are in the same layer."
It does not claim moral equivalence, and it does not claim that AI harm is
inevitable.
-/

-- Abstract typeclass for technologies that can produce non-admissible paths
-- and civilizational-scale consequences through such paths.
class CivilizationalResponsibilityTech (T : Type) : Prop where
  hasInadmissiblePath :
    Exists (fun p : RPath RObj.DH RObj.OR => Not (AdmBV p))
  hasCivilizationalConsequences :
    Exists (fun p : RPath RObj.DH RObj.OR =>
      Not (AdmBV p) /\ CivilizationalScale p)

-- Marker type for nuclear weapons in this formalization.
inductive NuclearWeapons where
  | marker : NuclearWeapons

-- Marker type for advanced AI systems in this formalization.
inductive AISystems where
  | marker : AISystems

-- Nuclear weapons are an instance of CivilizationalResponsibilityTech.
-- Historical referent: Hiroshima and Nagasaki, August 1945.
instance nuclearWeapons_is_crt :
    CivilizationalResponsibilityTech NuclearWeapons :=
  { hasInadmissiblePath := by
      cases hiroshima_historical_witness with
      | intro hwitness _ =>
          cases hwitness with
          | intro decision hprops =>
              cases hprops with
              | intro hNotAdm _ =>
                  exact Exists.intro decision hNotAdm
    hasCivilizationalConsequences := by
      cases hiroshima_historical_witness with
      | intro hwitness _ =>
          cases hwitness with
          | intro decision hprops =>
              cases hprops with
              | intro hNotAdm hscaleMem =>
                  cases hscaleMem with
                  | intro hScale _ =>
                      exact Exists.intro decision
                        (And.intro hNotAdm hScale) }

-- AI systems can produce an inadmissible path via `bypassBeaconPath`, already
-- proved non-admissible above.  Their civilizational-scale potential is an
-- explicit external premise, not a theorem of category theory.
axiom ai_has_civilizational_potential :
  Exists (fun p : RPath RObj.DH RObj.OR =>
    Not (AdmBV p) /\ CivilizationalScale p)

-- AI systems are an instance of CivilizationalResponsibilityTech.
-- Referent: Hiroshima AI Process (G7 2023) and international AI safety
-- evaluations concerning unchecked optimization and autonomous decisions.
instance ai_is_crt :
    CivilizationalResponsibilityTech AISystems :=
  { hasInadmissiblePath :=
      Exists.intro bypassBeaconPath bypassBeacon_not_admissible
    hasCivilizationalConsequences := ai_has_civilizational_potential }

-- Any instance of CivilizationalResponsibilityTech has a witness for an
-- inadmissible path.  This is substantive because it comes from a class field,
-- not from `True`.
theorem crt_has_inadmissible_path
    (T : Type) [CivilizationalResponsibilityTech T] :
    Exists (fun p : RPath RObj.DH RObj.OR => Not (AdmBV p)) :=
  CivilizationalResponsibilityTech.hasInadmissiblePath (T := T)

-- Any instance also has a civilizational-scale consequence witness through an
-- inadmissible path.
theorem crt_has_civilizational_consequence
    (T : Type) [CivilizationalResponsibilityTech T] :
    Exists (fun p : RPath RObj.DH RObj.OR =>
      Not (AdmBV p) /\ CivilizationalScale p) :=
  CivilizationalResponsibilityTech.hasCivilizationalConsequences (T := T)

-- Nuclear weapons and AI are in the same civilizational layer because both are
-- instances of the same abstract responsibility technology class.
theorem nuclear_ai_same_civilizational_layer :
    CivilizationalResponsibilityTech NuclearWeapons /\
    CivilizationalResponsibilityTech AISystems := by
  exact And.intro inferInstance inferInstance

-- For any CRT instance, its inadmissible path witness lives in the same fixed
-- responsibility category R.
theorem any_crt_has_inadmissible_path_in_R
    (T : Type) [CivilizationalResponsibilityTech T] :
    Exists (fun p : RPath RObj.DH RObj.OR => Not (AdmBV p)) :=
  CivilizationalResponsibilityTech.hasInadmissiblePath (T := T)

-- For any CRT instance, its civilizational-scale consequence witness also
-- lives in the same fixed responsibility category R.
theorem any_crt_has_civilizational_consequences_in_R
    (T : Type) [CivilizationalResponsibilityTech T] :
    Exists (fun p : RPath RObj.DH RObj.OR =>
      Not (AdmBV p) /\ CivilizationalScale p) :=
  CivilizationalResponsibilityTech.hasCivilizationalConsequences (T := T)

-- Nuclear weapons and AI share the same responsibility space R.  The claim is
-- not that two separate categories are isomorphic; it is that both sets of
-- witnesses live in this single responsibility category.
theorem nuclear_and_ai_share_responsibility_space :
    (Exists fun p : RPath RObj.DH RObj.OR =>
      Not (AdmBV p) /\ CivilizationalScale p) /\
    (Exists fun p : RPath RObj.DH RObj.OR => Not (AdmBV p)) := by
  exact And.intro
    (CivilizationalResponsibilityTech.hasCivilizationalConsequences
      (T := NuclearWeapons))
    (CivilizationalResponsibilityTech.hasInadmissiblePath
      (T := AISystems))

-- Any two CRT instances share the same target R for their inadmissible-path
-- witnesses.
theorem two_crts_share_R
    (T1 T2 : Type)
    [CivilizationalResponsibilityTech T1]
    [CivilizationalResponsibilityTech T2] :
    (Exists fun p1 : RPath RObj.DH RObj.OR => Not (AdmBV p1)) /\
    (Exists fun p2 : RPath RObj.DH RObj.OR => Not (AdmBV p2)) := by
  exact And.intro
    (CivilizationalResponsibilityTech.hasInadmissiblePath (T := T1))
    (CivilizationalResponsibilityTech.hasInadmissiblePath (T := T2))

/-!
### Why R_nuclear ~= R_ai is not needed

The responsibility category R is not parametric over T in this file.  R is the
fixed universal responsibility target for all CRT instances.  The correct
claim is not that two separate categories are isomorphic, but that there is one
R and all CRT instances provide their responsibility witnesses inside it.

`two_crts_share_R` formalizes this directly.
-/

/-!
## Conditioned Uniqueness of Hiroshima

Proves that Hiroshima is the only city satisfying both:

1. It received an intentional nuclear attack, not an accident.
2. It holds an internationally recognized AI governance anchor.

This does not prove that AI governance requires Hiroshima, nor that Hiroshima's
role is necessary for world adoption.  Those would be normative claims outside
formal proof.  The theorem below proves only a conditioned uniqueness statement
from explicit historical premises.
-/

-- A city type. `Other` represents all cities other than Hiroshima and
-- Nagasaki for the purpose of the exhaustiveness axiom below.
inductive City where
  | Hiroshima : City
  | Nagasaki : City
  | Other : City
  deriving DecidableEq, Repr

-- Predicate: the city received an intentional nuclear attack, not an accident.
axiom IntentionalNuclearAttack : City -> Prop

-- Predicate: the city holds an internationally recognized AI governance
-- anchor.
axiom AIGovernanceAnchor : City -> Prop

-- Hiroshima received an intentional nuclear attack.
-- Historical referent: August 6, 1945.
axiom nuclear_hiroshima : IntentionalNuclearAttack City.Hiroshima

-- Nagasaki received an intentional nuclear attack.
-- Historical referent: August 9, 1945.
axiom nuclear_nagasaki : IntentionalNuclearAttack City.Nagasaki

-- Hiroshima holds an AI governance anchor.
-- Historical referent: G7 Hiroshima AI Process (2023).
axiom anchor_hiroshima : AIGovernanceAnchor City.Hiroshima

-- Nagasaki does not hold an equivalent internationally recognized AI
-- governance anchor in this formal model.
axiom no_anchor_nagasaki : Not (AIGovernanceAnchor City.Nagasaki)

-- Exhaustiveness: intentional nuclear attacks occurred only at Hiroshima and
-- Nagasaki.  All other cities are excluded from this condition.
axiom nuclear_cities_exhaustive :
    forall x : City, IntentionalNuclearAttack x ->
      x = City.Hiroshima \/ x = City.Nagasaki

-- Hiroshima satisfies both conditions in this model.
theorem hiroshima_satisfies_conditioned_role :
    IntentionalNuclearAttack City.Hiroshima /\
    AIGovernanceAnchor City.Hiroshima := by
  exact And.intro nuclear_hiroshima anchor_hiroshima

-- Nagasaki satisfies the nuclear condition but not the AI-governance-anchor
-- condition in this model.
theorem nagasaki_has_nuclear_but_no_anchor :
    IntentionalNuclearAttack City.Nagasaki /\
    Not (AIGovernanceAnchor City.Nagasaki) := by
  exact And.intro nuclear_nagasaki no_anchor_nagasaki

-- Conditioned uniqueness of Hiroshima.
-- Among all cities that received an intentional nuclear attack, Hiroshima is
-- the only one that also holds an AI governance anchor.
theorem hiroshima_conditioned_unique :
    forall x : City,
      IntentionalNuclearAttack x /\ AIGovernanceAnchor x ->
      x = City.Hiroshima := by
  intro x h
  cases h with
  | intro h_nuclear h_anchor =>
      cases nuclear_cities_exhaustive x h_nuclear with
      | inl h_hiroshima =>
          exact h_hiroshima
      | inr h_nagasaki =>
          rw [h_nagasaki] at h_anchor
          exact False.elim (no_anchor_nagasaki h_anchor)

/-!
## Autonomous AI Logistics Requires AI Assurance

This section proves that any autonomous AI logistics system producing only
admissible decision paths must pass through Verification (V), which is the
formal content of AI assurance in this model.

The proof uses only `not_passV_not_admissible`, which is already proved in
this file.  No new axioms are introduced.

The argument:

1. An autonomous AI system makes decisions without constant human oversight.
   This creates the structural possibility of decision paths bypassing
   Verification.
2. By `not_passV_not_admissible`, any path bypassing V is not in AdmBV.
3. Therefore, for autonomous AI logistics to produce only admissible paths, it
   must pass through V.
4. Passing through V is the structural definition of AI assurance here.
5. By `hiroshima_conditioned_unique`, the city satisfying both the nuclear
   witness condition and the AI-governance-anchor condition is Hiroshima.

This does not restrict where AI logistics may be built or operated.  It claims
only that the structural basis for its responsibility architecture is uniquely
present in Hiroshima under the stated conditions.
-/

-- An autonomous AI logistics decision is modeled as a responsibility-category
-- path whose admissibility, rather than its autonomy alone, constrains it.
def AutonomousLogisticsDecision (_p : RPath RObj.DH RObj.OR) : Prop :=
  True

-- Core theorem: any autonomous AI logistics path bypassing Verification is not
-- admissible.  This is just `not_passV_not_admissible` specialized to
-- DH -> OR paths.
theorem autonomous_logistics_requires_verification :
    forall p : RPath RObj.DH RObj.OR,
      Not (passesThroughV p) ->
      Not (AdmBV p) :=
  not_passV_not_admissible

-- Corollary: for autonomous AI logistics to produce admissible paths, passage
-- through Verification (AI assurance) is structurally necessary.
theorem admissible_autonomous_logistics_needs_assurance :
    forall p : RPath RObj.DH RObj.OR,
      AdmBV p ->
      passesThroughV p := by
  intro p h_adm
  exact h_adm.right

-- Full structural chain: admissible autonomous AI logistics requires
-- Verification, and the conditioned uniqueness theorem identifies Hiroshima as
-- the city satisfying the stated historical/governance conditions.
theorem hiroshima_structural_basis_for_world_standard_ai_logistics :
    (forall p : RPath RObj.DH RObj.OR, AdmBV p -> passesThroughV p) /\
    (forall x : City,
      IntentionalNuclearAttack x /\ AIGovernanceAnchor x ->
      x = City.Hiroshima) := by
  exact And.intro
    admissible_autonomous_logistics_needs_assurance
    hiroshima_conditioned_unique

/-!
## Four-Stage Chain: Hiroshima as Origin of Next-Generation AI Logistics

Stage 1: Autonomous AI in logistics requires AI assurance.
         Already proved: `admissible_autonomous_logistics_needs_assurance`.

Stage 2: Hiroshima has conditioned uniqueness for AI assurance.
         Already proved: `hiroshima_conditioned_unique`.

Stage 3: If autonomous AI logistics is next-generation AI logistics, then
         there is a structural reason to develop its responsibility
         architecture from Hiroshima.

Stage 4: Hiroshima Prefecture has the physical and institutional environment
         for proof-of-concept implementation.

This does not claim that logistics systems cannot be built or operated
elsewhere.  It claims that the responsibility architecture, conditional
uniqueness, logistics infrastructure, and PoC environment converge in
Hiroshima under the stated assumptions.
-/

-- Next-generation AI logistics is defined as autonomous AI logistics whose
-- decision paths satisfy the admissibility condition AdmBV.
def NextGenAILogistics (p : RPath RObj.DH RObj.OR) : Prop :=
  AdmBV p

/-!
## Hiroshima Logistics Infrastructure Components

Hiroshima's world-class logistics base is not asserted as a single axiom.  It
is decomposed into documented components.  Their conjunction defines
`WorldLogisticsInfrastructure`, so `hiroshima_world_logistics` is a theorem,
not an axiom.
-/

-- Component 1: manufacturing hub with global supply chain.
axiom HasManufacturingHub : City -> Prop

-- Hiroshima is a manufacturing hub.
-- Referents: Mazda headquarters and global SCM, JIT manufacturing, parts supply
-- chain, shipbuilding legacy, and automotive supply-chain cluster.
axiom hiroshima_manufacturing_hub :
    HasManufacturingHub City.Hiroshima

-- Component 2: port infrastructure and Seto Inland Sea gateway.
axiom HasPortAndSeaGateway : City -> Prop

-- Hiroshima has port infrastructure and serves as an Asia gateway.
-- Referents: Hiroshima Port / Ujina international container terminal, Seto
-- Inland Sea distributed ports, RORO ships, Asia maritime routes, HIROSHIMA
-- FLOW, and Ujina's historical logistics role.
axiom hiroshima_port_gateway :
    HasPortAndSeaGateway City.Hiroshima

-- Component 3: maritime heritage and accumulated logistics knowledge.
axiom HasMaritimeHeritage : City -> Prop

-- Hiroshima has deep maritime heritage as a logistics foundation.
-- Referents: Murakami Suigun, Seto Inland Sea route management, military port
-- history, and shipbuilding legacy.
axiom hiroshima_maritime_heritage :
    HasMaritimeHeritage City.Hiroshima

-- Component 4: tourism and human-flow infrastructure.
axiom HasTourismHumanFlow : City -> Prop

-- Hiroshima has significant tourism and human-flow infrastructure.
-- Referents: Miyajima / Itsukushima Shrine, Peace Memorial Park, inbound
-- tourism, cruise arrivals, MaaS / route optimization potential, and HIROSHIMA
-- FLOW's tourism-logistics convergence.
axiom hiroshima_tourism_flow :
    HasTourismHumanFlow City.Hiroshima

-- Component 5: right-sized operational scale for integrated PoC.
-- The components above must not only exist; they must overlap at a scale that
-- makes integrated proof-of-concept implementation feasible.
axiom HasRightSizedOperationalScale : City -> Prop

-- Hiroshima has right-sized operational scale.
-- Referents: compact city structure, adjacent port / manufacturing / tourism /
-- human-flow sites, reachable cross-sector stakeholders, manageable industrial
-- and urban challenges, and easier coordination than in megacities.
axiom hiroshima_right_sized_scale :
    HasRightSizedOperationalScale City.Hiroshima

-- WorldLogisticsInfrastructure is a definition, not an axiom.
def WorldLogisticsInfrastructure (city : City) : Prop :=
  HasManufacturingHub city /\
  HasPortAndSeaGateway city /\
  HasMaritimeHeritage city /\
  HasTourismHumanFlow city /\
  HasRightSizedOperationalScale city

-- Hiroshima has world-class multi-modal logistics infrastructure.  This is now
-- a theorem proved from five documented component axioms.
theorem hiroshima_world_logistics :
    WorldLogisticsInfrastructure City.Hiroshima := by
  exact And.intro
    hiroshima_manufacturing_hub
    (And.intro
      hiroshima_port_gateway
      (And.intro
        hiroshima_maritime_heritage
        (And.intro
          hiroshima_tourism_flow
          hiroshima_right_sized_scale)))

-- Stage 3 theorem: Hiroshima is the unique city satisfying the structural
-- conditions for next-generation AI logistics.  The infrastructure condition
-- strengthens the premise; uniqueness already follows from the nuclear and AI
-- governance anchor conditions.
theorem hiroshima_unique_for_ai_logistics :
    forall x : City,
      IntentionalNuclearAttack x /\
      AIGovernanceAnchor x /\
      WorldLogisticsInfrastructure x ->
      x = City.Hiroshima := by
  intro x h
  cases h with
  | intro h_nuclear hrest =>
      cases hrest with
      | intro h_anchor _ =>
          exact hiroshima_conditioned_unique x
            (And.intro h_nuclear h_anchor)

-- Predicate: a city has the institutional and physical environment suitable
-- for proof-of-concept implementation of next-generation AI logistics.
axiom PoCEnvironment : City -> Prop

-- Hiroshima Prefecture has the environment for PoC implementation.
-- This is an external premise, not a theorem proved by category theory.
-- Referents include compact city scale, port / manufacturing / tourism
-- convergence, multi-sector collaboration, the Hiroshima AI Process, and the
-- OnZaLinx / GhostDrift pharmaceutical cold-chain PoC.
axiom hiroshima_poc_environment :
    PoCEnvironment City.Hiroshima

-- Complete four-stage structural chain.
theorem hiroshima_four_stage_ai_logistics_chain :
    -- Stage 1: next-generation AI logistics requires AI assurance.
    (forall p : RPath RObj.DH RObj.OR,
      NextGenAILogistics p -> passesThroughV p) /\
    -- Stage 2 + 3: Hiroshima is unique for this role.
    (forall x : City,
      IntentionalNuclearAttack x /\
      AIGovernanceAnchor x /\
      WorldLogisticsInfrastructure x ->
      x = City.Hiroshima) /\
    -- Stage 3 factual base: Hiroshima has logistics infrastructure.
    WorldLogisticsInfrastructure City.Hiroshima /\
    -- Stage 4: Hiroshima has the PoC environment.
    PoCEnvironment City.Hiroshima := by
  exact And.intro
    (fun p h_adm => admissible_autonomous_logistics_needs_assurance p h_adm)
    (And.intro
      hiroshima_unique_for_ai_logistics
      (And.intro
        hiroshima_world_logistics
        hiroshima_poc_environment))

end HiroshimaResponsibility
